dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://192.168.56.11:2181
  config-center:
    address: zookeeper://192.168.56.11:2181
  metadata-report:
    address: zookeeper://192.168.56.11:2181
server:
  port: 8083